name: Modern Tests

on:
  pull_request:
    paths:
      - 'tools/modern-tests/**'
      - 'packages/rspack/**'
      - 'packages/tools-core/**'
      - 'npm-packages/meteor-rspack/**'
      - 'tools/static-assets/skel-**'
      - '.github/workflows/modern-tests.yml'

jobs:
  test:
    name: ${{ matrix.category }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        category:
          - Babel
          - Blaze
          - Coffeescript
          - Monorepo
          - React
          - Solid
          - Svelte
          - Typescript
          - Vue

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
            packages/**/.npm
            .meteor
            dev_bundle
            .babel-cache
          key: ${{ runner.os }}-meteor-${{ hashFiles('**/package-lock.json', 'meteor') }}
          restore-keys: |
            ${{ runner.os }}-meteor-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install test deps
        run: npm install

      - name: Install test deps
        run: npm run install:modern

      - name: Install Playwright
        run: npx playwright install

      - name: Prepare Meteor
        run: ./meteor --get-ready

      - name: Run tests for ${{ matrix.category }}
        env:
          METEOR_WATCH_FORCE_POLLING: "true"
          METEOR_WATCH_POLLING_INTERVAL_MS: "1000"
        run: npm run test:modern -- -t="${{ matrix.category }}"
